import type { CountryCode } from './phone-input';

export const countryCodes: CountryCode[] = [
  {
    name: 'Afghanistan',
    code: '+93',
    image: '🇦🇫',
    short: 'AF',
  },
  {
    name: 'Aland Islands',
    code: '+358',
    image: '🇦🇽',
    short: 'AX',
  },
  {
    name: 'Albania',
    code: '+355',
    image: '🇦🇱',
    short: 'AL',
  },
  {
    name: 'Algeria',
    code: '+213',
    image: '🇩🇿',
    short: 'DZ',
  },
  {
    name: 'AmericanSamoa',
    code: '+1684',
    image: '🇦🇸',
    short: 'AS',
  },
  {
    name: 'Andorra',
    code: '+376',
    image: '🇦🇩',
    short: 'AD',
  },
  {
    name: 'Angola',
    code: '+244',
    image: '🇦🇴',
    short: 'AO',
  },
  {
    name: 'Anguilla',
    code: '+1264',
    image: '🇦🇮',
    short: 'AI',
  },
  {
    name: 'Antarctica',
    code: '+672',
    image: '🇦🇶',
    short: 'AQ',
  },
  {
    name: 'Antigua and Barbuda',
    code: '+1268',
    image: '🇦🇬',
    short: 'AG',
  },
  {
    name: 'Argentina',
    code: '+54',
    image: '🇦🇷',
    short: 'AR',
  },
  {
    name: 'Armenia',
    code: '+374',
    image: '🇦🇲',
    short: 'AM',
  },
  {
    name: 'Aruba',
    code: '+297',
    image: '🇦🇼',
    short: 'AW',
  },
  {
    name: 'Australia',
    code: '+61',
    image: '🇦🇺',
    short: 'AU',
  },
  {
    name: 'Austria',
    code: '+43',
    image: '🇦🇹',
    short: 'AT',
  },
  {
    name: 'Azerbaijan',
    code: '+994',
    image: '🇦🇿',
    short: 'AZ',
  },
  {
    name: 'Bahamas',
    code: '+1242',
    image: '🇧🇸',
    short: 'BS',
  },
  {
    name: 'Bahrain',
    code: '+973',
    image: '🇧🇭',
    short: 'BH',
  },
  {
    name: 'Bangladesh',
    code: '+880',
    image: '🇧🇩',
    short: 'BD',
  },
  {
    name: 'Barbados',
    code: '+1246',
    image: '🇧🇧',
    short: 'BB',
  },
  {
    name: 'Belarus',
    code: '+375',
    image: '🇧🇾',
    short: 'BY',
  },
  {
    name: 'Belgium',
    code: '+32',
    image: '🇧🇪',
    short: 'BE',
  },
  {
    name: 'Belize',
    code: '+501',
    image: '🇧🇿',
    short: 'BZ',
  },
  {
    name: 'Benin',
    code: '+229',
    image: '🇧🇯',
    short: 'BJ',
  },
  {
    name: 'Bermuda',
    code: '+1441',
    image: '🇧🇲',
    short: 'BM',
  },
  {
    name: 'Bhutan',
    code: '+975',
    image: '🇧🇹',
    short: 'BT',
  },
  {
    name: 'Bolivia, Plurinational State of',
    code: '+591',
    image: '🇧🇴',
    short: 'BO',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: '+387',
    image: '🇧🇦',
    short: 'BA',
  },
  {
    name: 'Botswana',
    code: '+267',
    image: '🇧🇼',
    short: 'BW',
  },
  {
    name: 'Brazil',
    code: '+55',
    image: '🇧🇷',
    short: 'BR',
  },
  {
    name: 'British Indian Ocean Territory',
    code: '+246',
    image: '🇮🇴',
    short: 'IO',
  },
  {
    name: 'Brunei Darussalam',
    code: '+673',
    image: '🇧🇳',
    short: 'BN',
  },
  {
    name: 'Bulgaria',
    code: '+359',
    image: '🇧🇬',
    short: 'BG',
  },
  {
    name: 'Burkina Faso',
    code: '+226',
    image: '🇧🇫',
    short: 'BF',
  },
  {
    name: 'Burundi',
    code: '+257',
    image: '🇧🇮',
    short: 'BI',
  },
  {
    name: 'Cambodia',
    code: '+855',
    image: '🇰🇭',
    short: 'KH',
  },
  {
    name: 'Cameroon',
    code: '+237',
    image: '🇨🇲',
    short: 'CM',
  },
  {
    name: 'Canada',
    code: '+1',
    image: '🇨🇦',
    short: 'CA',
  },
  {
    name: 'Cape Verde',
    code: '+238',
    image: '🇨🇻',
    short: 'CV',
  },
  {
    name: 'Cayman Islands',
    code: '+345',
    image: '🇰🇾',
    short: 'KY',
  },
  {
    name: 'Central African Republic',
    code: '+236',
    image: '🇨🇫',
    short: 'CF',
  },
  {
    name: 'Chad',
    code: '+235',
    image: '🇹🇩',
    short: 'TD',
  },
  {
    name: 'Chile',
    code: '+56',
    image: '🇨🇱',
    short: 'CL',
  },
  {
    name: 'China',
    code: '+86',
    image: '🇨🇳',
    short: 'CN',
  },
  {
    name: 'Christmas Island',
    code: '+61',
    image: '🇨🇽',
    short: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: '+61',
    image: '🇨🇨',
    short: 'CC',
  },
  {
    name: 'Colombia',
    code: '+57',
    image: '🇨🇴',
    short: 'CO',
  },
  {
    name: 'Comoros',
    code: '+269',
    image: '🇰🇲',
    short: 'KM',
  },
  {
    name: 'Congo',
    code: '+242',
    image: '🇨🇬',
    short: 'CG',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    code: '+243',
    image: '🇨🇩',
    short: 'CD',
  },
  {
    name: 'Cook Islands',
    code: '+682',
    image: '🇨🇰',
    short: 'CK',
  },
  {
    name: 'Costa Rica',
    code: '+506',
    image: '🇨🇷',
    short: 'CR',
  },
  {
    name: "Cote d'Ivoire",
    code: '+225',
    image: '🇨🇮',
    short: 'CI',
  },
  {
    name: 'Croatia',
    code: '+385',
    image: '🇭🇷',
    short: 'HR',
  },
  {
    name: 'Cuba',
    code: '+53',
    image: '🇨🇺',
    short: 'CU',
  },
  {
    name: 'Cyprus',
    code: '+357',
    image: '🇨🇾',
    short: 'CY',
  },
  {
    name: 'Czech Republic',
    code: '+420',
    image: '🇨🇿',
    short: 'CZ',
  },
  {
    name: 'Denmark',
    code: '+45',
    image: '🇩🇰',
    short: 'DK',
  },
  {
    name: 'Djibouti',
    code: '+253',
    image: '🇩🇯',
    short: 'DJ',
  },
  {
    name: 'Dominica',
    code: '+1767',
    image: '🇩🇲',
    short: 'DM',
  },
  {
    name: 'Dominican Republic',
    code: '+1849',
    image: '🇩🇴',
    short: 'DO',
  },
  {
    name: 'Ecuador',
    code: '+593',
    image: '🇪🇨',
    short: 'EC',
  },
  {
    name: 'Egypt',
    code: '+20',
    image: '🇪🇬',
    short: 'EG',
  },
  {
    name: 'El Salvador',
    code: '+503',
    image: '🇸🇻',
    short: 'SV',
  },
  {
    name: 'Equatorial Guinea',
    code: '+240',
    image: '🇬🇶',
    short: 'GQ',
  },
  {
    name: 'Eritrea',
    code: '+291',
    image: '🇪🇷',
    short: 'ER',
  },
  {
    name: 'Estonia',
    code: '+372',
    image: '🇪🇪',
    short: 'EE',
  },
  {
    name: 'Ethiopia',
    code: '+251',
    image: '🇪🇹',
    short: 'ET',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code: '+500',
    image: '🇫🇰',
    short: 'FK',
  },
  {
    name: 'Faroe Islands',
    code: '+298',
    image: '🇫🇴',
    short: 'FO',
  },
  {
    name: 'Fiji',
    code: '+679',
    image: '🇫🇯',
    short: 'FJ',
  },
  {
    name: 'Finland',
    code: '+358',
    image: '🇫🇮',
    short: 'FI',
  },
  {
    name: 'France',
    code: '+33',
    image: '🇫🇷',
    short: 'FR',
  },
  {
    name: 'French Guiana',
    code: '+594',
    image: '🇬🇫',
    short: 'GF',
  },
  {
    name: 'French Polynesia',
    code: '+689',
    image: '🇵🇫',
    short: 'PF',
  },
  {
    name: 'Gabon',
    code: '+241',
    image: '🇬🇦',
    short: 'GA',
  },
  {
    name: 'Gambia',
    code: '+220',
    image: '🇬🇲',
    short: 'GM',
  },
  {
    name: 'Georgia',
    code: '+995',
    image: '🇬🇪',
    short: 'GE',
  },
  {
    name: 'Germany',
    code: '+49',
    image: '🇩🇪',
    short: 'DE',
  },
  {
    name: 'Ghana',
    code: '+233',
    image: '🇬🇭',
    short: 'GH',
  },
  {
    name: 'Gibraltar',
    code: '+350',
    image: '🇬🇮',
    short: 'GI',
  },
  {
    name: 'Greece',
    code: '+30',
    image: '🇬🇷',
    short: 'GR',
  },
  {
    name: 'Greenland',
    code: '+299',
    image: '🇬🇱',
    short: 'GL',
  },
  {
    name: 'Grenada',
    code: '+1473',
    image: '🇬🇩',
    short: 'GD',
  },
  {
    name: 'Guadeloupe',
    code: '+590',
    image: '🇬🇵',
    short: 'GP',
  },
  {
    name: 'Guam',
    code: '+1671',
    image: '🇬🇺',
    short: 'GU',
  },
  {
    name: 'Guatemala',
    code: '+502',
    image: '🇬🇹',
    short: 'GT',
  },
  {
    name: 'Guernsey',
    code: '+44',
    image: '🇬🇬',
    short: 'GG',
  },
  {
    name: 'Guinea',
    code: '+224',
    image: '🇬🇳',
    short: 'GN',
  },
  {
    name: 'Guinea-Bissau',
    code: '+245',
    image: '🇬🇼',
    short: 'GW',
  },
  {
    name: 'Guyana',
    code: '+595',
    image: '🇬🇾',
    short: 'GY',
  },
  {
    name: 'Haiti',
    code: '+509',
    image: '🇭🇹',
    short: 'HT',
  },
  {
    name: 'Holy See (Vatican City State)',
    code: '+379',
    image: '🇻🇦',
    short: 'VA',
  },
  {
    name: 'Honduras',
    code: '+504',
    image: '🇭🇳',
    short: 'HN',
  },
  {
    name: 'Hong Kong',
    code: '+852',
    image: '🇭🇰',
    short: 'HK',
  },
  {
    name: 'Hungary',
    code: '+36',
    image: '🇭🇺',
    short: 'HU',
  },
  {
    name: 'Iceland',
    code: '+354',
    image: '🇮🇸',
    short: 'IS',
  },
  {
    name: 'India',
    code: '+91',
    image: '🇮🇳',
    short: 'IN',
  },
  {
    name: 'Indonesia',
    code: '+62',
    image: '🇮🇩',
    short: 'ID',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    code: '+98',
    image: '🇮🇷',
    short: 'IR',
  },
  {
    name: 'Iraq',
    code: '+964',
    image: '🇮🇷',
    short: 'IQ',
  },
  {
    name: 'Ireland',
    code: '+353',
    image: '🇮🇪',
    short: 'IE',
  },
  {
    name: 'Isle of Man',
    code: '+44',
    image: '🇮🇲',
    short: 'IM',
  },
  {
    name: 'Israel',
    code: '+972',
    image: '🇮🇱',
    short: 'IL',
  },
  {
    name: 'Italy',
    code: '+39',
    image: '🇮🇹',
    short: 'IT',
  },
  {
    name: 'Jamaica',
    code: '+1876',
    image: '🇯🇲',
    short: 'JM',
  },
  {
    name: 'Japan',
    code: '+81',
    image: '🇯🇵',
    short: 'JP',
  },
  {
    name: 'Jersey',
    code: '+44',
    image: '🇯🇪',
    short: 'JE',
  },
  {
    name: 'Jordan',
    code: '+962',
    image: '🇯🇴',
    short: 'JO',
  },
  {
    name: 'Kazakhstan',
    code: '+77',
    image: '🇰🇿',
    short: 'KZ',
  },
  {
    name: 'Kenya',
    code: '+254',
    image: '🇰🇪',
    short: 'KE',
  },
  {
    name: 'Kiribati',
    code: '+686',
    image: '🇰🇮',
    short: 'KI',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    code: '+850',
    image: '🇰🇵',
    short: 'KP',
  },
  {
    name: 'Korea, Republic of South Korea',
    code: '+82',
    image: '🇰🇷',
    short: 'KR',
  },
  {
    name: 'Kuwait',
    code: '+965',
    image: '🇰🇼',
    short: 'KW',
  },
  {
    name: 'Kyrgyzstan',
    code: '+996',
    image: '🇰🇬',
    short: 'KG',
  },
  {
    name: 'Laos',
    code: '+856',
    image: '🇱🇦',
    short: 'LA',
  },
  {
    name: 'Latvia',
    code: '+371',
    image: '🇱🇻',
    short: 'LV',
  },
  {
    name: 'Lebanon',
    code: '+961',
    image: '🇱🇧',
    short: 'LB',
  },
  {
    name: 'Lesotho',
    code: '+266',
    image: '🇱🇸',
    short: 'LS',
  },
  {
    name: 'Liberia',
    code: '+231',
    image: '🇱🇷',
    short: 'LR',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    code: '+218',
    image: '🇱🇾',
    short: 'LY',
  },
  {
    name: 'Liechtenstein',
    code: '+423',
    image: '🇱🇮',
    short: 'LI',
  },
  {
    name: 'Lithuania',
    code: '+370',
    image: '🇱🇹',
    short: 'LT',
  },
  {
    name: 'Luxembourg',
    code: '+352',
    image: '🇱🇺',
    short: 'LU',
  },
  {
    name: 'Macao',
    code: '+853',
    image: '🇲🇴',
    short: 'MO',
  },
  {
    name: 'Macedonia',
    code: '+389',
    image: '🇲🇰',
    short: 'MK',
  },
  {
    name: 'Madagascar',
    code: '+261',
    image: '🇲🇬',
    short: 'MG',
  },
  {
    name: 'Malawi',
    code: '+265',
    image: '🇲🇼',
    short: 'MW',
  },
  {
    name: 'Malaysia',
    code: '+60',
    image: '🇲🇾',
    short: 'MY',
  },
  {
    name: 'Maldives',
    code: '+960',
    image: '🇲🇻',
    short: 'MV',
  },
  {
    name: 'Mali',
    code: '+223',
    image: '🇲🇱',
    short: 'ML',
  },
  {
    name: 'Malta',
    code: '+356',
    image: '🇲🇹',
    short: 'MT',
  },
  {
    name: 'Marshall Islands',
    code: '+692',
    image: '🇲🇭',
    short: 'MH',
  },
  {
    name: 'Martinique',
    code: '+596',
    image: '🇲🇶',
    short: 'MQ',
  },
  {
    name: 'Mauritania',
    code: '+222',
    image: '🇲🇷',
    short: 'MR',
  },
  {
    name: 'Mauritius',
    code: '+230',
    image: '🇲🇺',
    short: 'MU',
  },
  {
    name: 'Mayotte',
    code: '+262',
    image: '🇾🇹',
    short: 'YT',
  },
  {
    name: 'Mexico',
    code: '+52',
    image: '🇲🇽',
    short: 'MX',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    code: '+691',
    image: '🇫🇲',
    short: 'FM',
  },
  {
    name: 'Moldova',
    code: '+373',
    image: '🇲🇩',
    short: 'MD',
  },
  {
    name: 'Monaco',
    code: '+377',
    image: '🇲🇨',
    short: 'MC',
  },
  {
    name: 'Mongolia',
    code: '+976',
    image: '🇲🇳',
    short: 'MN',
  },
  {
    name: 'Montenegro',
    code: '+382',
    image: '🇲🇪',
    short: 'ME',
  },
  {
    name: 'Montserrat',
    code: '+1664',
    image: '🇲🇸',
    short: 'MS',
  },
  {
    name: 'Morocco',
    code: '+212',
    image: '🇲🇦',
    short: 'MA',
  },
  {
    name: 'Mozambique',
    code: '+258',
    image: '🇲🇿',
    short: 'MZ',
  },
  {
    name: 'Myanmar',
    code: '+95',
    image: '🇲🇲',
    short: 'MM',
  },
  {
    name: 'Namibia',
    image: '🇳🇦',
    code: '+264',
    short: 'NA',
  },
  {
    name: 'Nauru',
    code: '+674',
    image: '🇳🇷',
    short: 'NR',
  },
  {
    name: 'Nepal',
    code: '+977',
    image: '🇳🇵',
    short: 'NP',
  },
  {
    name: 'Netherlands',
    code: '+31',
    image: '🇳🇱',
    short: 'NL',
  },
  {
    name: 'Netherlands Antilles',
    code: '+599',
    image: '🇧🇶',
    short: 'AN',
  },
  {
    name: 'New Caledonia',
    code: '+687',
    image: '🇳🇨',
    short: 'NC',
  },
  {
    name: 'New Zealand',
    code: '+64',
    image: '🇳🇿',
    short: 'NZ',
  },
  {
    name: 'Nicaragua',
    code: '+505',
    image: '🇳🇮',
    short: 'NI',
  },
  {
    name: 'Niger',
    code: '+227',
    image: '🇳🇪',
    short: 'NE',
  },
  {
    name: 'Nigeria',
    code: '+234',
    image: '🇳🇬',
    short: 'NG',
  },
  {
    name: 'Niue',
    code: '+683',
    image: '🇳🇺',
    short: 'NU',
  },
  {
    name: 'Norfolk Island',
    code: '+672',
    image: '🇳🇫',
    short: 'NF',
  },
  {
    name: 'Northern Mariana Islands',
    code: '+1670',
    image: '🇲🇵',
    short: 'MP',
  },
  {
    name: 'Norway',
    code: '+47',
    image: '🇳🇴',
    short: 'NO',
  },
  {
    name: 'Oman',
    code: '+968',
    image: '🇴🇲',
    short: 'OM',
  },
  {
    name: 'Pakistan',
    code: '+92',
    image: '🇵🇰',
    short: 'PK',
  },
  {
    name: 'Palau',
    code: '+680',
    image: '🇵🇼',
    short: 'PW',
  },
  {
    name: 'Palestinian Territory, Occupied',
    code: '+970',
    image: '🇵🇸',
    short: 'PS',
  },
  {
    name: 'Panama',
    code: '+507',
    image: '🇵🇦',
    short: 'PA',
  },
  {
    name: 'Papua New Guinea',
    code: '+675',
    image: '🇵🇬',
    short: 'PG',
  },
  {
    name: 'Paraguay',
    code: '+595',
    image: '🇵🇾',
    short: 'PY',
  },
  {
    name: 'Peru',
    code: '+51',
    image: '🇵🇪',
    short: 'PE',
  },
  {
    name: 'Philippines',
    code: '+63',
    image: '🇵🇭',
    short: 'PH',
  },
  {
    name: 'Pitcairn',
    code: '+872',
    image: '🇵🇳',
    short: 'PN',
  },
  {
    name: 'Poland',
    code: '+48',
    image: '🇵🇱',
    short: 'PL',
  },
  {
    name: 'Portugal',
    code: '+351',
    image: '🇵🇹',
    short: 'PT',
  },
  {
    name: 'Puerto Rico',
    code: '+1939',
    image: '🇵🇷',
    short: 'PR',
  },
  {
    name: 'Qatar',
    code: '+974',
    image: '🇶🇦',
    short: 'QA',
  },
  {
    name: 'Romania',
    code: '+40',
    image: '🇷🇴',
    short: 'RO',
  },
  {
    name: 'Russia',
    code: '+7',
    image: '🇷🇺',
    short: 'RU',
  },
  {
    name: 'Rwanda',
    code: '+250',
    image: '🇷🇼',
    short: 'RW',
  },
  {
    name: 'Reunion',
    code: '+262',
    image: '🇷🇪',
    short: 'RE',
  },
  {
    name: 'Saint Barthelemy',
    code: '+590',
    image: '🇧🇱',
    short: 'BL',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    code: '+290',
    image: '🇸🇭',
    short: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: '+1869',
    image: '🇰🇳',
    short: 'KN',
  },
  {
    name: 'Saint Lucia',
    code: '+1758',
    image: '🇱🇨',
    short: 'LC',
  },
  {
    name: 'Saint Martin',
    code: '+590',
    image: '🇲🇫',
    short: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: '+508',
    image: '🇵🇲',
    short: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: '+1784',
    image: '🇻🇨',
    short: 'VC',
  },
  {
    name: 'Samoa',
    code: '+685',
    image: '🇼🇸',
    short: 'WS',
  },
  {
    name: 'San Marino',
    code: '+378',
    image: '🇸🇲',
    short: 'SM',
  },
  {
    name: 'Sao Tome and Principe',
    code: '+239',
    image: '🇸🇹',
    short: 'ST',
  },
  {
    name: 'Saudi Arabia',
    code: '+966',
    image: '🇸🇦',
    short: 'SA',
  },
  {
    name: 'Senegal',
    code: '+221',
    image: '🇸🇳',
    short: 'SN',
  },
  {
    name: 'Serbia',
    code: '+381',
    image: '🇷🇸',
    short: 'RS',
  },
  {
    name: 'Seychelles',
    code: '+248',
    image: '🇸🇨',
    short: 'SC',
  },
  {
    name: 'Sierra Leone',
    code: '+232',
    image: '🇸🇱',
    short: 'SL',
  },
  {
    name: 'Singapore',
    code: '+65',
    image: '🇸🇬',
    short: 'SG',
  },
  {
    name: 'Slovakia',
    code: '+421',
    image: '🇸🇰',
    short: 'SK',
  },
  {
    name: 'Slovenia',
    code: '+386',
    image: '🇸🇮',
    short: 'SI',
  },
  {
    name: 'Solomon Islands',
    code: '+677',
    image: '🇸🇧',
    short: 'SB',
  },
  {
    name: 'Somalia',
    code: '+252',
    image: '🇸🇴',
    short: 'SO',
  },
  {
    name: 'South Africa',
    code: '+27',
    image: '🇿🇦',
    short: 'ZA',
  },
  {
    name: 'South Sudan',
    code: '+211',
    image: '🇸🇸',
    short: 'SS',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: '+500',
    image: '🇬🇸',
    short: 'GS',
  },
  {
    name: 'Spain',
    code: '+34',
    image: '🇪🇸',
    short: 'ES',
  },
  {
    name: 'Sri Lanka',
    code: '+94',
    image: '🇱🇰',
    short: 'LK',
  },
  {
    name: 'Sudan',
    code: '+249',
    image: '🇸🇩',
    short: 'SD',
  },
  {
    name: 'Suriname',
    code: '+597',
    image: '🇸🇷',
    short: 'SR',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: '+47',
    image: '🇸🇯',
    short: 'SJ',
  },
  {
    name: 'Swaziland',
    code: '+268',
    image: '🇸🇿',
    short: 'SZ',
  },
  {
    name: 'Sweden',
    code: '+46',
    image: '🇸🇪',
    short: 'SE',
  },
  {
    name: 'Switzerland',
    code: '+41',
    image: '🇨🇭',
    short: 'CH',
  },
  {
    name: 'Syrian Arab Republic',
    code: '+963',
    image: '🇸🇾',
    short: 'SY',
  },
  {
    name: 'Taiwan',
    code: '+886',
    image: '🇹🇼',
    short: 'TW',
  },
  {
    name: 'Tajikistan',
    code: '+992',
    image: '🇹🇯',
    short: 'TJ',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    code: '+255',
    image: '🇹🇿',
    short: 'TZ',
  },
  {
    name: 'Thailand',
    code: '+66',
    image: '🇹🇭',
    short: 'TH',
  },
  {
    name: 'Timor-Leste',
    code: '+670',
    image: '🇹🇱',
    short: 'TL',
  },
  {
    name: 'Togo',
    code: '+228',
    image: '🇹🇬',
    short: 'TG',
  },
  {
    name: 'Tokelau',
    code: '+690',
    image: '🇹🇰',
    short: 'TK',
  },
  {
    name: 'Tonga',
    code: '+676',
    image: '🇹🇴',
    short: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    code: '+1868',
    image: '🇹🇹',
    short: 'TT',
  },
  {
    name: 'Tunisia',
    code: '+216',
    image: '🇹🇳',
    short: 'TN',
  },
  {
    name: 'Turkey',
    code: '+90',
    image: '🇹🇷',
    short: 'TR',
  },
  {
    name: 'Turkmenistan',
    code: '+993',
    image: '🇹🇲',
    short: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    code: '+1649',
    image: '🇹🇨',
    short: 'TC',
  },
  {
    name: 'Tuvalu',
    code: '+688',
    image: '🇹🇻',
    short: 'TV',
  },
  {
    name: 'Uganda',
    code: '+256',
    image: '🇺🇬',
    short: 'UG',
  },
  {
    name: 'Ukraine',
    code: '+380',
    image: '🇺🇦',
    short: 'UA',
  },
  {
    name: 'United Arab Emirates',
    code: '+971',
    image: '🇦🇪',
    short: 'AE',
  },
  {
    name: 'United Kingdom',
    code: '+44',
    image: '🇬🇧',
    short: 'GB',
  },
  {
    name: 'United States',
    code: '+1',
    image: '🇺🇸',
    short: 'US',
  },
  {
    name: 'Uruguay',
    code: '+598',
    image: '🇺🇾',
    short: 'UY',
  },
  {
    name: 'Uzbekistan',
    code: '+998',
    image: '🇺🇿',
    short: 'UZ',
  },
  {
    name: 'Vanuatu',
    code: '+678',
    image: '🇻🇺',
    short: 'VU',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    code: '+58',
    image: '🇻🇪',
    short: 'VE',
  },
  {
    name: 'Vietnam',
    code: '+84',
    image: '🇻🇳',
    short: 'VN',
  },
  {
    name: 'Virgin Islands, British',
    code: '+1284',
    image: '🇻🇬',
    short: 'VG',
  },
  {
    name: 'Virgin Islands, U.S.',
    code: '+1340',
    image: '🇻🇮',
    short: 'VI',
  },
  {
    name: 'Wallis and Futuna',
    code: '+681',
    image: '🇼🇫',
    short: 'WF',
  },
  {
    name: 'Yemen',
    code: '+967',
    image: '🇾🇪',
    short: 'YE',
  },
  {
    name: 'Zambia',
    code: '+260',
    image: '🇿🇲',
    short: 'ZM',
  },
  {
    name: 'Zimbabwe',
    code: '+263',
    image: '🇿🇼',
    short: 'ZW',
  },
];
